import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Bell, Box, Check, CheckCircle2, ChevronDown, ChevronRight, Clock3, ClipboardList, Download, LayoutDashboard, LogOut, MapPin, Package, Plus, Search, ShieldCheck, Sparkles, Truck, TrendingUp, X } from 'lucide-react';
import { useAuth } from '../../app/providers/AuthProvider';
import { getValidAccessToken } from '../../lib/blocks/auth';
import './desk.css';
import { NetworkData } from './NetworkData';

type Person = { id: string; name: string; role: string; hub?: string; label?: string };
type Incident = { id: string; parcelId: string; cod?: number; senderName?: string; type?: string; hub?: string; route?: string; lastHandler?: string; owner?: Person; openedAt?: string; status: string; pendingTransfer?: { recipient: Person; from: string }; note?: string; analysis?: any; nextStep?: string; history?: any[]; publicUpdates: any[]; sla?: { hours: number; state: string } };
type Workspace = { version: number; demo: boolean; principal: Person; people: Person[]; cases: Incident[]; routes: any[]; decisions: any[]; aiConfigured: boolean };
const personas = [{ id: 'hub-mirpur', name: 'Nabila · Mirpur hub' }, { id: 'rider-jashim', name: 'Jashim · Rider' }, { id: 'care-ayesha', name: 'Ayesha · Care' }, { id: 'hub-ctg', name: 'Rafi · Destination hub' }, { id: 'ops-farhan', name: 'Farhan · Ops manager' }, { id: 'sender-nova', name: 'Nova Fashion · Sender' }];
const money = (n?: number) => n === undefined ? 'Not linked' : `৳${n.toLocaleString('en-BD')}`;
const date = (s?: string) => s ? new Date(s).toLocaleString('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) : '—';
const initials = (name = '') => name.split(' ').slice(0, 2).map(s => s[0]).join('');
const Badge = ({ value }: { value: string }) => <span className={'badge ' + (value === 'Breached' || value === 'High risk' ? 'red' : value === 'At risk' || value === 'Pending' ? 'amber' : value === 'Resolved' || value === 'Stable' ? 'green' : 'neutral')}>{value}</span>;

export function Desk() {
  const auth = useAuth();
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [persona, setPersona] = useState(sessionStorage.getItem('poth-persona') || 'hub-mirpur');
  const [page, setPage] = useState('desk');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All cases');
  const [hubFilter, setHubFilter] = useState('All hubs');
  const [selected, setSelected] = useState<string | null>(null);
  const [showNew, setShowNew] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [busy, setBusy] = useState(false);
  const [note, setNote] = useState('');
  const [nextStep, setNextStep] = useState('');
  const [recipient, setRecipient] = useState('');
  const [outcome, setOutcome] = useState('Delivered');
  const [reviewed, setReviewed] = useState(false);
  const [analyticsGroup, setAnalyticsGroup] = useState('route');
  async function apiHeaders(json = false) {
    const token = await getValidAccessToken();
    return { 'X-Demo-Persona': persona, ...(json ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) };
  }
  async function refresh() {
    try {
      const res = await fetch('/api/workspace', { headers: await apiHeaders() });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setWorkspace(data); setError('');
    } catch (e) { setError((e as Error).message); }
  }
  useEffect(() => { setWorkspace(null); setSelected(null); sessionStorage.setItem('poth-persona', persona); void refresh(); const timer = setInterval(refresh, 30000); return () => clearInterval(timer); }, [persona]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); } }, [toast]);
  const item = workspace?.cases.find(c => c.id === selected);
  useEffect(() => { setNote(item?.note || ''); setNextStep(item?.nextStep || item?.analysis?.recommendation || ''); setReviewed(false); setRecipient(''); }, [selected, item?.analysis]);
  async function action(name: string, body: Record<string, unknown> = {}) {
    if (!workspace || busy) return;
    setBusy(true); setError('');
    try {
      const res = await fetch('/api/actions/' + name, { method: 'POST', headers: await apiHeaders(true), body: JSON.stringify({ ...body, version: workspace.version }) });
      const data = await res.json(); if (!res.ok) throw new Error(data.error);
      await refresh(); setToast(name === 'acknowledge' ? 'Ownership accepted. The handoff is recorded.' : name === 'transfer' ? 'Handoff requested. You remain the owner until acknowledgement.' : 'Saved successfully.');
      if (name === 'create') { setShowNew(false); setSelected(data.id); }
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  const p = workspace?.principal;
  const sender = p?.role === 'sender';
  const cases = workspace?.cases || [];
  const open = cases.filter(c => c.status !== 'Resolved');
  const breached = open.filter(c => c.sla?.state === 'Breached');
  const pending = open.filter(c => c.pendingTransfer);
  const shown = cases.filter(c => (!query || [c.id, c.parcelId, c.owner?.name, c.senderName].join(' ').toLowerCase().includes(query.toLowerCase())) && (hubFilter === 'All hubs' || c.hub === hubFilter) && (filter === 'All cases' || filter === 'Open' && c.status !== 'Resolved' || filter === 'SLA breached' && c.sla?.state === 'Breached' || filter === 'Awaiting handoff' && c.pendingTransfer || filter === 'Resolved' && c.status === 'Resolved'));
  const title = sender ? 'Your deliveries' : page === 'routes' ? 'Route intelligence' : page === 'handoffs' ? 'Ownership & handoffs' : 'Exception desk';
  function exportData() {
    const csv = ['Case,Parcel,Status,Owner,Hub,SLA', ...shown.map(c => [c.id, c.parcelId, c.status, c.owner?.name || '', c.hub || '', c.sla?.state || ''].map(v => '"' + String(v).replace(/"/g, '""').replace(/^[=+@-]/, "'$&") + '"').join(','))].join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const a = document.createElement('a'); a.href = url; a.download = 'pathaopoth-cases.csv'; a.click(); URL.revokeObjectURL(url);
  }
  const lead = [...(workspace?.routes || [])].sort((a, b) => (b.change || 0) - (a.change || 0))[0];
  const routeRows = analyticsGroup === 'route' ? workspace?.routes || [] : Object.values((workspace?.routes || []).reduce((groups: Record<string, any>, r: any) => { const name = r[analyticsGroup]; const g = groups[name] ||= { route: name, volume: 0, exceptions: 0, previousVolume: 0, previousExceptions: 0 }; for (const k of ['volume', 'exceptions', 'previousVolume', 'previousExceptions']) g[k] += r[k]; g.rate = 100 * g.exceptions / g.volume; g.change = (g.rate / (100 * g.previousExceptions / g.previousVolume) - 1) * 100; return groups; }, {}));
  return <div className="poth-app">
    <aside className="sidebar">
      <a className="brand" href="/" aria-label="PathaoPoth home"><span className="brand-mark"><Package size={23} /></span><span>Pathao<span className="brand-light">Poth</span><small>DELIVERY OPERATIONS</small></span></a>
      <div className="workspace-chip"><span className="workspace-icon">P</span><div>PathaoPoth Operations<small>Bangladesh network</small></div><ChevronDown size={14} /></div>
      <span className="nav-label">WORKSPACE</span>
      <button className={'nav-link ' + (page === 'desk' ? 'active' : '')} onClick={() => { setPage('desk'); setFilter('All cases'); }}><LayoutDashboard size={18} />{sender ? 'My deliveries' : 'Exception desk'}<span className="nav-count">{open.length}</span></button>
      {!sender && <><button className={'nav-link ' + (page === 'handoffs' ? 'active' : '')} onClick={() => { setPage('handoffs'); setFilter('Awaiting handoff'); }}><ArrowRight size={18} />Handoffs{pending.length > 0 && <span className="nav-count">{pending.length}</span>}</button><button className="nav-link" onClick={() => { setPage('desk'); setFilter('SLA breached'); }}><Clock3 size={18} />SLA monitor<span className="red-dot" /></button></>}
      {p?.role === 'ops' && <><span className="nav-label">INTELLIGENCE</span><button className={'nav-link ' + (page === 'routes' ? 'active' : '')} onClick={() => setPage('routes')}><TrendingUp size={18} />Route intelligence</button></>}
      <div className="sidebar-bottom"><div className="help-card"><ShieldCheck size={21} /><strong>Every parcel. One owner.</strong><p>Clear accountability, all the way to resolution.</p></div><div className="account"><span className="avatar">{initials(p?.name || 'Demo User')}</span><div>{p?.name || 'Signing in…'}<small>{p?.label || p?.role || 'Blocks account'}</small></div><button title="Sign out" aria-label="Sign out" onClick={() => void auth.logout()}><LogOut size={17} /></button></div></div>
    </aside>
    <div className="main-wrap"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14} /><strong>{title}</strong></div><div className="top-actions"><span className="live-dot" />System operational<button title="Show pending handoffs" aria-label="Show pending handoffs" onClick={() => { setPage('handoffs'); setFilter('Awaiting handoff'); }}><Bell size={18} /></button><span className="avatar small">{initials(p?.name || 'DU')}</span></div></header>
      <main className="desk-main">
        {workspace?.demo && <div className="demo-bar"><span><span className="demo-pill">DEMO WORKSPACE</span> Sample parcels · changes are saved</span><label>Experience as <select aria-label="Demo persona" value={persona} onChange={e => { setPage('desk'); setFilter('All cases'); setPersona(e.target.value); }}>{personas.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label></div>}
        <div className="page-heading"><div><div className="eyebrow">{sender ? 'SENDER PORTAL' : page === 'routes' ? 'SEE THE PATTERN. PREVENT THE NEXT FAILURE.' : 'DELIVERY EXCEPTION MANAGEMENT'}</div><h1>{title}<span className="heading-dot">.</span></h1><p>{sender ? 'Clear updates on your parcels, without the back-and-forth.' : page === 'routes' ? 'Turn repeated delivery failures into your next operational decision.' : 'Keep parcels moving. Give every exception a clear next step.'}</p></div><div className="heading-actions">{!sender && <button className="secondary" onClick={exportData}><Download size={16} /> Export</button>}{['hub', 'care'].includes(p?.role || '') && <button className="primary" onClick={() => setShowNew(true)}><Plus size={17} /> New exception</button>}</div></div>
        {error && <div role="alert" className="error-banner">{error}<button onClick={() => void refresh()}>Retry</button></div>}
        {!workspace && !error && <div className="loading-panel">Loading your workspace…</div>}
        {workspace && (sender ? <div className="sender-grid">{shown.map(c => <article className="panel sender-card" key={c.id}><div className="section-title"><Package size={22} /><strong>{c.parcelId}</strong><Badge value={c.status} /></div><h3>Your parcel is in good hands</h3><div className="timeline">{c.publicUpdates.map((u, i) => <div className="timeline-row" key={i}><span className="timeline-dot"><Check size={12} /></span><div><small>{date(u.at)}</small><p>{u.message}</p>{u.expectedResolution && <small>Expected update by {date(u.expectedResolution)}</small>}</div></div>)}</div><div className="privacy-note"><ShieldCheck size={14} /> Only verified, sender-safe updates appear here.</div></article>)}</div> : page === 'routes' && p?.role === 'ops' ? <>
          {lead && <div className="route-hero panel"><div><span className="eyebrow"><Sparkles size={15} /> NEXT-WEEK OUTLOOK</span><h2>{lead.route}<br />{lead.risk === 'High risk' ? 'needs a pre-call plan.' : 'is ready for review.'}</h2><p>{lead.evidence}</p><div className="hero-badges"><Badge value={lead.risk} /><span>Statistical forecast{workspace.demo ? ' · sample data' : ' · imported measurements'}</span></div><button className="primary" disabled={busy || workspace.decisions.some(d => d.route === lead.route)} onClick={() => void action('precall', { route: lead.route })}>{workspace.decisions.some(d => d.route === lead.route) ? <><Check size={16} /> Pre-call plan created</> : <>Create pre-call plan <ArrowUpRight size={16} /></>}</button></div><div className="forecast-chart"><span>EXCEPTION RATE · RECENT MEASUREMENTS</span><div className="chart-bars">{(lead.weeklyRates || [100 * lead.previousExceptions / lead.previousVolume, lead.rate]).map((v: number, i: number) => <div key={i}><strong>{v.toFixed(2)}%</strong><i style={{ height: `${v * 42}px` }} /><small>Week {i + 1}</small></div>)}</div><p><strong>{lead.change > 0 ? '+' : ''}{lead.change?.toFixed(1)}%</strong> exception rate vs. previous week</p></div></div>}
          <div className="panel"><div className="panel-heading"><div><h2>Network performance</h2><p>Rates use all network parcel volumes as denominators.</p></div><select aria-label="Group analytics" value={analyticsGroup} onChange={e => setAnalyticsGroup(e.target.value)}><option value="route">By route</option><option value="hub">By hub</option><option value="rider">By rider</option></select></div><div className="table-scroll"><table><thead><tr><th>{analyticsGroup}</th><th>Parcel volume</th><th>Exceptions</th><th>Exception rate</th><th>Week over week</th><th>Outlook</th></tr></thead><tbody>{routeRows.map((r: any) => <tr key={r.route}><td className="strong">{r.route}</td><td>{r.volume.toLocaleString()}</td><td>{r.exceptions}</td><td>{r.rate?.toFixed(2) ?? '—'}%</td><td className={r.change > 0 ? 'text-red' : 'text-green'}>{r.change > 0 ? '+' : ''}{r.change?.toFixed(1) ?? '—'}%</td><td><Badge value={r.risk || (r.change > 20 ? 'High risk' : 'Stable')} /></td></tr>)}</tbody></table></div></div>
          <NetworkData save={action} busy={busy} />
          <div className="evidence-grid">{workspace.routes.map(r => <article className="panel evidence-card" key={r.route}><div className="section-title"><MapPin size={17} /><strong>{r.route}</strong></div><p>{r.evidence}</p><div className="prediction"><small>Next-week estimated rate</small><strong>{r.predictedRate?.toFixed(2)}%</strong><span>Indicative interval {r.interval?.[0].toFixed(2)}–{r.interval?.[1].toFixed(2)}%</span></div><small>{r.method}</small></article>)}</div>
          {workspace.decisions.length > 0 && <section className="panel decisions"><h2>Operational decisions</h2>{workspace.decisions.map(d => <div key={d.id}><CheckCircle2 size={20} /><div><strong>{d.route}</strong><p>{d.action}</p><small>{d.owner} · {date(d.at)} · {d.status}</small></div></div>)}</section>}
        </> : <>
          <section className="metrics"><Metric label="Open exceptions" value={open.length} icon={<Package size={19} />} note="Every case has a named owner" /><Metric label="SLA breached" value={breached.length} icon={<Clock3 size={19} />} note="Past the 72-hour threshold" tone="red" /><Metric label="Awaiting handoff" value={pending.length} icon={<ArrowRight size={19} />} note="Current owner stays accountable" tone="amber" /><Metric label="Resolved" value={cases.length - open.length} icon={<CheckCircle2 size={19} />} note="Closed with a recorded outcome" tone="green" /></section>
          <div className="insight-strip"><span className="insight-icon"><Sparkles size={19} /></span><div><strong>{pending.length ? `${pending.length} handoff${pending.length > 1 ? 's' : ''} waiting for acknowledgement` : 'A clear next step starts with a better incident note'}</strong><p>{pending.length ? 'The receiving team must accept before ownership changes.' : 'Structure rough rider notes, review the evidence, and confirm an action.'}</p></div><button onClick={() => { const target = pending[0] || cases.find(c => c.note); if (target) setSelected(target.id); }}>{pending.length ? 'Review handoffs' : 'Review a case'} <ArrowRight size={16} /></button></div>
          <section className="panel case-panel"><div className="panel-heading"><h2>{page === 'handoffs' ? 'Handoff queue' : 'All exceptions'} <span className="count-label">{cases.length}</span></h2><span className="updated"><span className="live-dot" /> Updates every 30 seconds</span></div><div className="tabs">{['All cases', 'Open', 'SLA breached', 'Awaiting handoff', 'Resolved'].map(tab => <button key={tab} onClick={() => setFilter(tab)} className={filter === tab ? 'selected' : ''}>{tab}{tab === 'SLA breached' && <span>{breached.length}</span>}</button>)}</div><div className="table-tools"><label className="search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search case, parcel, sender or owner…" /></label><select aria-label="Filter by hub" value={hubFilter} onChange={e => setHubFilter(e.target.value)}><option>All hubs</option>{Array.from(new Set(cases.map(c => c.hub))).filter(Boolean).map(h => <option key={h}>{h}</option>)}</select><span className="results">{shown.length} cases</span></div><div className="table-scroll"><table><thead><tr><th>Case / Parcel</th><th>Exception</th><th>Hub & route</th><th>Owner</th><th>Age / SLA</th><th>Status</th><th /></tr></thead><tbody>{shown.map((c, i) => <tr key={c.id} onClick={() => setSelected(c.id)}><td><button className="case-link" onClick={() => setSelected(c.id)}>{c.id}</button><small>{c.parcelId} <span className="table-dot">·</span> {money(c.cod)}</small></td><td><span className={'type-icon t' + i % 4}>{c.type === 'Refused delivery' ? <X size={12} /> : c.type === 'Damaged' ? <Box size={12} /> : <Clock3 size={12} />}</span>{c.type}</td><td><span>{c.hub}</span><small>{c.route || 'Route not linked'}</small></td><td><div className="owner-cell"><span className={'avatar a' + i % 4}>{initials(c.owner?.name)}</span><div>{c.owner?.name}<small>{c.owner?.label || c.owner?.role}</small></div></div></td><td><span className={c.sla?.state === 'Breached' ? 'text-red' : ''}>{c.sla?.hours}h</span><small className={c.sla?.state === 'Breached' ? 'text-red' : ''}>{c.sla?.state}</small></td><td><Badge value={c.pendingTransfer ? 'Pending' : c.status} /></td><td><ChevronRight size={16} /></td></tr>)}</tbody></table></div>{!shown.length && <div className="empty"><ClipboardList size={30} /><h3>No cases in this view</h3><p>Try another filter, or open a new exception.</p></div>}<div className="table-footer">Showing {shown.length} of {cases.length} scoped cases<span><ShieldCheck size={14} /> Access scoped to your role</span></div></section>
          <div className="bottom-note"><span><span className="live-dot" /> Ownership is continuous. No case is left unassigned.</span><span>All times shown in your local timezone</span></div>
        </>)}
      </main>
    </div>
    {toast && <div className="toast" role="status"><CheckCircle2 size={19} />{toast}</div>}
    {item && !sender && <div className="drawer-overlay" onClick={() => setSelected(null)}><section className="drawer" role="dialog" aria-modal="true" aria-label={`Case ${item.id}`} onClick={e => e.stopPropagation()}><header className="drawer-header"><div><span className="eyebrow">EXCEPTION DETAILS</span><h2>{item.id}</h2></div><button className="icon-button" aria-label="Close case" onClick={() => setSelected(null)}><X size={22} /></button></header><div className="drawer-body"><div className="case-summary"><span className="package-tile"><Package size={27} /></span><div><h3>{item.parcelId}</h3><p>{item.type} · COD {money(item.cod)}</p></div><Badge value={item.status} /></div><div className="detail-grid"><div><small>CURRENT OWNER</small><strong>{item.owner?.name}</strong></div><div><small>HUB</small><strong>{item.hub}</strong></div><div><small>LAST HANDLER</small><strong>{item.lastHandler}</strong></div><div><small>CASE AGE</small><strong>{item.sla?.hours}h · {item.sla?.state}</strong></div></div>
      {item.pendingTransfer && <div className="handoff-alert"><strong>Awaiting {item.pendingTransfer.recipient.name}'s acknowledgement</strong><p>{item.owner?.name} remains accountable.</p>{item.pendingTransfer.recipient.id === p?.id && <button disabled={busy} className="primary" onClick={() => void action('acknowledge', { id: item.id })}><Check size={16} /> Accept ownership</button>}</div>}
      {item.status !== 'Resolved' && <><section className="drawer-section"><div className="section-title"><ClipboardList size={17} /><h3>Rider's raw note</h3><span className="subtle-tag">Internal only</span></div><textarea aria-label="Rider note" value={note} onChange={e => setNote(e.target.value)} placeholder="Bangla, Banglish, or English — capture what happened." rows={4} maxLength={10000} disabled={!['rider', 'hub', 'care'].includes(p?.role || '')} /><div className="button-row">{['rider', 'hub', 'care'].includes(p?.role || '') && <button className="secondary" disabled={busy || !note.trim()} onClick={() => void action('note', { id: item.id, note })}>Save note</button>}{['hub', 'care'].includes(p?.role || '') && <button className="primary" disabled={busy || !item.note || item.note !== note} onClick={() => void action('analyze', { id: item.id })}><Sparkles size={16} /> Structure incident</button>}</div></section>
      {item.analysis && <section className="analysis-box"><div className="section-title"><Sparkles size={17} /><h3>Incident brief</h3><span className="subtle-tag">{Math.round(item.analysis.confidence * 100)}% confidence</span></div><div className="analysis-grid"><div><small>ATTEMPTS</small><strong>{item.analysis.attempts ?? 'Unknown'}</strong></div><div><small>AVAILABILITY</small><strong>{item.analysis.availability}</strong></div><div><small>FAILURE REASON</small><strong>{item.analysis.failureReason}</strong></div><div><small>ADDRESS QUALITY</small><strong>{item.analysis.addressQuality}</strong></div></div><p className="manual-review">{item.analysis.manualReview ? 'Manual review required' : 'Ready for care review'} · {item.analysis.source}</p><small>{item.analysis.limitation}</small><details><summary>View supporting evidence</summary><blockquote>{item.analysis.evidence}</blockquote></details><label className="field-label">Recommended next step<textarea value={nextStep} onChange={e => setNextStep(e.target.value)} rows={3} disabled={p?.role !== 'care'} /></label>{p?.role === 'care' && <><label className="review-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /> I reviewed the rider's evidence and next step.</label><button className="primary" disabled={busy || !reviewed} onClick={() => void action('confirm', { id: item.id, nextStep, reviewed })}><CheckCircle2 size={16} /> Confirm next step</button></>}</section>}
      {item.owner?.id === p?.id && !item.pendingTransfer && <section className="drawer-section"><div className="section-title"><ArrowRight size={17} /><h3>Transfer ownership</h3></div><p>You remain the owner until the receiving person accepts.</p><div className="button-row"><select aria-label="Receiving staff member" value={recipient} onChange={e => setRecipient(e.target.value)}><option value="">Choose a receiving person</option>{workspace?.people.filter(person => person.id !== p?.id && ['hub', 'care'].includes(person.role)).map(person => <option key={person.id} value={person.id}>{person.name} · {person.label || person.role}</option>)}</select><button className="secondary" disabled={busy || !recipient} onClick={() => void action('transfer', { id: item.id, recipientId: recipient })}>Request handoff</button></div></section>}</>}
      <section className="drawer-section"><div className="section-title"><Clock3 size={17} /><h3>Ownership & activity trail</h3></div><div className="timeline">{item.history?.map((e, i) => <div key={i} className="timeline-row"><span className={'timeline-dot ' + (e.kind === 'transfer-acknowledged' ? 'accepted' : '')}><Check size={12} /></span><div><strong>{e.actor}</strong><small>{date(e.at)}{e.to ? ` · ${e.from ? e.from + ' → ' : ''}${e.to}` : ''}</small><p>{e.message}</p></div></div>)}</div></section>
      <section className="drawer-section"><div className="section-title"><ShieldCheck size={17} /><h3>Sender-visible updates</h3></div>{item.publicUpdates.map((u, i) => <div className="public-update" key={i}><small>{date(u.at)}</small><p>{u.message}</p></div>)}</section>
      {item.status !== 'Resolved' && item.owner?.id === p?.id && !item.pendingTransfer && <div className="resolve-box"><select aria-label="Resolution outcome" value={outcome} onChange={e => setOutcome(e.target.value)}><option>Delivered</option><option>Returned to sender</option><option>Claim settled</option></select><button className="primary" disabled={busy} onClick={() => void action('resolve', { id: item.id, outcome })}><CheckCircle2 size={16} /> Resolve case</button></div>}
      </div></section></div>}
    {showNew && <div className="modal-overlay" onClick={() => setShowNew(false)}><section className="new-modal" role="dialog" aria-modal="true" aria-label="New exception" onClick={e => e.stopPropagation()}><div className="panel-heading"><div><span className="eyebrow">FOUR FIELDS. ONE ACCOUNTABLE OWNER.</span><h2>Open an exception</h2></div><button aria-label="Close new exception" className="icon-button" onClick={() => setShowNew(false)}><X size={21} /></button></div><form onSubmit={e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); void action('create', data); }}><label>Parcel ID<input name="parcelId" placeholder="PP-826500" required maxLength={100} defaultValue={workspace?.demo ? 'PP-826500' : ''} /></label>{workspace?.demo && <p className="form-hint">Demo parcel: Nova Fashion · COD ৳2,300 · Mirpur → Chattogram</p>}<label>Exception type<select name="type">{['Refused delivery', 'Delayed', 'Damaged', 'Address missing', 'Sender dispute'].map(t => <option key={t}>{t}</option>)}</select></label><label>Current hub<select name="hub" defaultValue={p?.hub || 'Mirpur 10'}>{(p?.role === 'hub' ? [p.hub!] : ['Mirpur 10', 'Chattogram GEC', 'Moghbazar']).map(h => <option key={h}>{h}</option>)}</select></label><label>Last handler<input name="lastHandler" placeholder="Rider or staff member" required maxLength={100} defaultValue={workspace?.demo ? 'Jashim Uddin' : ''} /></label><div className="owner-notice"><ShieldCheck size={17} /> You, {p?.name}, will own this case.</div><button className="primary full" disabled={busy}><Plus size={17} />{busy ? 'Opening…' : 'Open exception'}</button></form></section></div>}
  </div>;
}
function Metric({ label, value, icon, note, tone = '' }: { label: string; value: number; icon: React.ReactNode; note: string; tone?: string }) { return <article className={'metric ' + tone}><div className="metric-top"><span>{label}</span><i>{icon}</i></div><strong>{value.toString().padStart(2, '0')}</strong><small>{note}</small></article>; }

export function PothLogin() {
  const { login } = useAuth(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <div className="poth-login"><div className="login-story"><a className="brand" href="/"><span className="brand-mark"><Package size={25} /></span><span>PathaoPoth</span></a><div><span className="eyebrow">THE DELIVERY EXCEPTION DESK</span><h1>Every parcel<br />has a way<br /><em>forward.</em></h1><p>From the first failed attempt to the final handoff.<br />One clear owner. One shared picture.</p><div className="login-route"><MapPin /><span>Mirpur</span><i /><Truck /><i /><span>Chattogram</span><CheckCircle2 /></div></div><small>Built for the people who keep Bangladesh moving.</small></div><div className="login-form"><div className="login-card"><span className="brand-mark"><Package size={24} /></span><h2>Welcome to your desk.</h2><p>Sign in to keep your deliveries moving.</p><div className="login-feature"><ShieldCheck size={20} /><div><strong>Your workspace, securely scoped</strong><p>Hub staff, riders, care, operations, and senders each see what they need.</p></div></div>{error && <div className="error-banner">{error}</div>}<button className="primary full" disabled={busy} onClick={() => { setBusy(true); void login('/').catch(e => { setError(e.message); setBusy(false); }); }}>{busy ? 'Opening secure sign-in…' : 'Sign in with Blocks'}<ArrowRight size={18} /></button><small className="login-footnote">You’ll continue to the secure Blocks sign-in page.</small></div></div></div>;
}
