import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
if (!process.env.PATHAO_TEST_PASSWORD) throw new Error('Set PATHAO_TEST_PASSWORD to the demo password for the browser test.');
mkdirSync('artifacts', { recursive: true });
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1024 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto('https://pbngdj-elhjx.slsblx.com:5173');
await page.getByRole('button', { name: 'Sign in with Blocks' }).click();
await page.locator('input[type=email]').fill('demouser140826@yopmail.com');
await page.locator('input[type=password]').fill(process.env.PATHAO_TEST_PASSWORD);
await page.locator('input[type=password]').press('Enter');
await page.getByRole('button', { name: 'New exception' }).waitFor({ timeout: 60000 });
await page.screenshot({ path: 'artifacts/pathaopoth-overview.png', fullPage: true });
async function mutation(button) {
  const response = page.waitForResponse(r => r.url().includes('/api/actions/') && r.request().method() === 'POST');
  await button.click(); const r = await response; assert.equal(r.status(), 200, await r.text());
  await page.waitForResponse(r => r.url().includes('/api/workspace') && r.status() === 200);
}
async function persona(id) {
  await page.getByLabel('Demo persona').selectOption(id);
  await page.waitForResponse(r => r.url().includes('/api/workspace') && r.status() === 200);
}
await page.getByRole('button', { name: 'New exception' }).click();
await mutation(page.getByRole('button', { name: 'Open exception', exact: true }));
const dialog = page.locator('.drawer');
await dialog.waitFor();
const caseId = await dialog.locator('h2').innerText();
console.log('Created four-field case:', caseId);
await page.getByLabel('Rider note').fill('3 bar gesi, customer phone off chilo. Guard dhukte dey nai. Duita kalo building, address clear na. Customer bole shondha 7tar por thakbe, COD 2300 ready korbe.');
await mutation(page.getByRole('button', { name: 'Save note', exact: true }));
await mutation(page.getByRole('button', { name: 'Structure incident' }));
await page.getByText('Manual review required', { exact: false }).waitFor();
await page.getByLabel('Receiving staff member').selectOption('care-ayesha');
await mutation(page.getByRole('button', { name: 'Request handoff' }));
assert.ok((await dialog.innerText()).includes('Nabila Rahman remains accountable.'));
await page.getByLabel('Close case', { exact: true }).click();
await persona('care-ayesha');
await page.getByRole('button', { name: caseId, exact: true }).click();
await mutation(page.getByRole('button', { name: 'Accept ownership' }));
await page.getByLabel("I reviewed the rider's evidence and next step.").check();
await mutation(page.getByRole('button', { name: 'Confirm next step' }));
await page.getByLabel('Receiving staff member').selectOption('hub-ctg');
await mutation(page.getByRole('button', { name: 'Request handoff' }));
assert.ok((await dialog.innerText()).includes('Ayesha Khan remains accountable.'));
await page.getByLabel('Close case', { exact: true }).click();
await persona('hub-ctg');
await page.getByRole('button', { name: caseId, exact: true }).click();
await mutation(page.getByRole('button', { name: 'Accept ownership' }));
await page.screenshot({ path: 'artifacts/pathaopoth-handoff.png', fullPage: true });
await mutation(page.getByRole('button', { name: 'Resolve case' }));
assert.ok((await dialog.innerText()).includes('Handoff acknowledged. Ownership accepted.'));
await page.getByLabel('Close case', { exact: true }).click();
await page.reload();
await page.getByRole('button', { name: caseId, exact: true }).waitFor({ timeout: 30000 });
console.log('Persisted both handoffs, care confirmation, and resolution after reload.');
await persona('sender-nova');
const senderResponse = await page.evaluate(async () => (await fetch('/api/workspace', { headers: { 'X-Demo-Persona': 'sender-nova' } })).json());
assert.ok(senderResponse.cases.every(c => !('note' in c) && !('owner' in c) && !('receiverPhone' in c) && !('history' in c)));
assert.equal(senderResponse.people.length, 0);
console.log('Sender API response omits all internal fields.');
await persona('ops-farhan');
await page.getByRole('button', { name: 'Route intelligence', exact: true }).click();
await page.getByText('Network performance', { exact: true }).waitFor();
const preCall = page.getByRole('button', { name: 'Create pre-call plan' });
if (await preCall.count()) await mutation(preCall);
await page.screenshot({ path: 'artifacts/pathaopoth-routes.png', fullPage: true });
await page.getByLabel('Group analytics').selectOption('hub');
await page.getByLabel('Group analytics').selectOption('rider');
console.log('Route, hub, rider analytics and pre-call plan verified.');
await page.setViewportSize({ width: 390, height: 844 });
await persona('hub-mirpur');
await page.screenshot({ path: 'artifacts/pathaopoth-mobile.png', fullPage: true });
const dimensions = await page.evaluate(() => ({ viewport: innerWidth, scroll: document.documentElement.scrollWidth }));
assert.ok(dimensions.scroll <= dimensions.viewport, JSON.stringify(dimensions));
assert.deepEqual(errors, []);
console.log('Mobile page has no horizontal overflow; no browser errors.');
await browser.close();

